export const GET_MY_ROOMS = 'GET_MY_ROOMS'

export const GET_HARDWARE_HISTORIES = 'GET_HARDWARE_HISTORIES'

export const GET_POWER_WATER_HISTORIES = 'GET_POWER_WATER_HISTORIES'

export const GET_HARDWARE_LIMIT = 'GET_HARDWARE_LIMIT'

export const GET_NEW_UPDATED_ROOM_NAME = 'GET_NEW_UPDATED_ROOM_NAME'
